### ISSUE TITLE
Refactor things named as "Events" to "Sessions" 

### ISSUE THREAD

**Issue by jurvis** [fossasia/open-event-ios#11]
confusing naming, just have to rename things that are incorrectly named as "events" to "sessions"

**Comment by jurvis** [comment]
currently assigned to @todipratik  - can't assign him to this issue because he's not added to the org.

(can anyone help? cc// @mariobehling @creativepsyco @hpdang @leto)

**Comment by mariobehling** [comment]
As architecture is planned to change to use a number of JSON files or API, I am closing this issue. Please refer to info on JSON/API here: https://github.com/fossasia/open-event
