### ISSUE TITLE
Unable to Run project on local

### ISSUE THREAD

**Issue by xorforce** [fossasia/open-event-ios#21]
Hi there, just starting my open source journey and wanted some help running project on my local machine. Here is the error I'm getting with cocoapods.
![screen shot 2016-08-25 at 1 10 01 am](https://cloud.githubusercontent.com/assets/14857735/17945346/0b9f1f46-6a61-11e6-988c-da70845f075f.png)

**Comment by mariobehling** [comment]
Project is getting updated to Swift 3. Please test again and reopen if needed. Please join us in http://codeheat.org.
