### ISSUE TITLE
Project is broken :/

### ISSUE THREAD

**Issue by xorforce** [fossasia/open-event-ios#29]
Project has a pod "Pages" which is not updated for swift 3 which gives around ~45 errors at buildtime. Should the pod be updated or a new pod be selected?
![screen shot 2016-10-20 at 6 25 45 pm](https://cloud.githubusercontent.com/assets/14857735/19560577/ac7f9284-96f2-11e6-95e1-11bb50b683f8.png)

**Comment by mariobehling** [comment]
@xorforce Sorry, but "project is broken" is not an issue. There is already a similarly undefined issue where you commented and I reposted your comment there https://github.com/fossasia/open-event-ios/issues/28

Please post specific issues and bugs, e.g. "Update to Swift 3".

Closing this issue therefore.
