### ISSUE TITLE
initial load doesn't load stuff onto EventsViewController

### ISSUE THREAD

**Issue by jurvis** [fossasia/open-event-ios#3]
on first run, the data loads but tableView doesn't reload with the new data. 

temporary workaround: restart the app and things will load.

**Comment by SilentFlame** [comment]
would like to work on this.
Can you please guide me as to what and where I should look for this issue.

**Comment by jurvis** [comment]
@SilentFlame  sure, most of the persisting of events are done in FossAsiaEventsService which conforms to EventsServiceProtocol. The events get loaded whenever a View Model instantiates FossAsiaEventsService.

My method to persist the events within the device is quick and dirty:
1. Check if this is first run via NSUserDefaults. If yes, go to 2, else go to 3.
2. Get events from network request and persist it to documents directory with file name events.json
3. Read events.json off disk on documents directory
4. Return result via completionHandler
 
You shouldn't have to touch anything beyond FossAsiaEventsService, I'd imagine. If you have any more questions, feel free to put them on here or reaching out via Slack.

Thanks for volunteering! I'll put up more issues with things to build as soon I can get more time off the Chinese New Year chaos :smile:

**Comment by jurvis** [comment]
issue has been fixed in commit 29bd4667fdf3d3c954a85b2c89b25457bbe76d2f
