### ISSUE TITLE
Nothing loads, the spinner just keeps spinning.

### ISSUE THREAD

**Issue by dannymout** [fossasia/open-event-ios#32]
## Description
I'm trying to run the app on my computer, and when testing it in the simulator, the spinner just keeps spinning, no info ever loads. This is a link to a GIF I took of the behaviour: http://imgur.com/a/e4mKy

## Environment
iOS 10.1 _(iPhone 7 Plus)_ Simulator
Xcode 8.1

## Steps to Reproduce

1. Clone repo and run `pod install`
2. Open xcworkspace
3. Go to File > Convert > To Current Swift Syntax and select Swift 3
4. Update files that Xcode suggest should be updated to Swift 3
5. Clean, build and run project

When, I run the app I see a spinning loader and nothing happens, assuming it should update with information. Also, Xcode doesn't see any network activity in the app.
<img width="300" src="http://i.imgur.com/RthxcPX.png">

**Comment by chashmeetsingh** [comment]
@dannymout its not supposed to, as nothing is configured neither parsing the data from the API as the project was put on hold 😄
