### ISSUE TITLE
generates tonnes of errors on build

### ISSUE THREAD

**Issue by ashwini0529** [fossasia/open-event-ios#35]

**Comment by chashmeetsingh** [comment]
Hi,
If you are trying to build this on xcode 8 then check https://github.com/fossasia/open-event-ios/issues/28
I am not sure about xcode 9 as I haven't tried to build for that

**Comment by raghavbabbar** [comment]
Hi, 
Is anyone working on it?
if yes then what is status ?

**Comment by chashmeetsingh** [comment]
@raghavbabbar currently no one is working on it. If you want, you can start this.

**Comment by raghavbabbar** [comment]
ok Sure.

**Comment by jurvis** [comment]
i've looked into the build errors and have isolated it to `Pages` as an outdated dependency. thanks for all your participation, I'm closing this issue in favour for the one I've created with a better description of going on: https://github.com/fossasia/open-event-ios/issues/38
