### ISSUE TITLE
Podfile, Manifest and Sandbox  Error

### ISSUE THREAD

**Issue by debbarmaonit** [fossasia/open-event-ios#4]
I have just now imported the project but it is not running and giving Three Errors , Screenshot is below 
<img width="1280" alt="screen shot 2016-02-13 at 1 20 07 pm" src="https://cloud.githubusercontent.com/assets/16494109/13026620/64dc3bde-d254-11e5-977f-f85f66b4d7d3.png">

**Comment by debbarmaonit** [comment]
I have tried updating Cocoapods, but doesnot help.

**Comment by todipratik** [comment]
Did you install the dependencies? You can install by running following command:
**pod install**

**Comment by jurvis** [comment]
@debbarmaonit sorry about not having put up setup instructions beforehand, I've just updated the README with clearer instructions in fbdd78fa57e98050af9e4c7bc1c1ba9e0cb706a7. 

Please make sure that you've run `pod install` on the root directory of the repository and open the project using the **.xcworkspace** file and not .xcodeproj. Thanks for trying!
