### ISSUE TITLE
Update 2016.fossasia.org link to 2018.fossasia.org.

### ISSUE THREAD

**Issue by imjog** [fossasia/open-event-ios#40]
On More tab it is showing link **2016.fossasia.org** and opening the the same link. It should be update to **2018.fossasia.org**.
![simulator screen shot - iphone 7 - 2017-10-28 at 03 48 21](https://user-images.githubusercontent.com/20956124/32130692-c10812b0-bbba-11e7-8b44-413069dd357a.png)

 **can I update this?** thanks :)

**Comment by jurvis** [comment]
:+1: do it!

**Comment by imjog** [comment]
@jurvis It is good if i do it in swift 4 version?
