### ISSUE TITLE
2016.fossasia.org link is not aligned on More Tab

### ISSUE THREAD

**Issue by imjog** [fossasia/open-event-ios#41]
the link is un aligned due to some wrong constraint. Now looking like this:
![simulator screen shot - iphone 7 - 2017-10-28 at 03 48 21](https://user-images.githubusercontent.com/20956124/32130717-4f708bea-bbbb-11e7-81e3-27007f7ea459.png)

It should be proper aligned. I want to work on this issue.

**Comment by jurvis** [comment]
:+1: Good spotting. Go ahead!

**Comment by imjog** [comment]
@jurvis  👍
