### ISSUE TITLE
Swift 4 version

### ISSUE THREAD

**Issue by imjog** [fossasia/open-event-ios#42]
this is written in older version of swift. should we migrate it into latest version Swift 4.
we can create new branch for swift for version or we can put in a folder. Need your suggestions. thanks :)

**Comment by jurvis** [comment]
I will be keen on starting a work on migrating the project to Swift 4!

The way I see it is to do it in these steps:
1. Run project through migrator
2. Update project dependencies to use a Swift 4 version whenever possible, else we can run it in legacy Swift 3.2 mode
3. Get project to build
4. Fix regressions wherever they might exist

I’m keen to work on 1-3 then put up a swift-4 branch on the master repo for anyone to fork and fix bugs. 

However, while I do have push access to the repo, I haven’t been contributing to the project for awhile now, so I’ll love @mariobehling’s input on my suggestion.

**Comment by chashmeetsingh** [comment]
Hey @jurvis, it's better if you fork the repo and make changes in it. After that send a PR and we can review it before merging. As Mario stated before, try not to create branches in the main repo.

**Comment by jurvis** [comment]
@chashmeetsingh the Swift upgrade is a rather large source + project setup change, so I feel like it makes sense for it to have it's own working branch in the master repo before it gets merged into anything. 

This will allow contributors should be able to fork a working `swift-4` branch to fix any potential regressions while other changes can still be made on the old project that uses the older swift version -- no?

**Comment by imjog** [comment]
Hey @chashmeetsingh when i created this issue, i worked on this and successfully migrated it to swift 4. I was waiting for review and suggestion. can i send a PR now?
