### ISSUE TITLE
Features list

### ISSUE THREAD

**Issue by mananwason** [fossasia/open-event-ios#5]
@jurvis @creativepsyco It would be better to have a list of features we are targeting. We can then take up some issues and contribute more effectively.

**Comment by jurvis** [comment]
added a contributing.md and uploaded a set of designs with the basic features in fbdd78fa57e98050af9e4c7bc1c1ba9e0cb706a7

**Comment by mananwason** [comment]
Awesome @jurvis :+1:

**Comment by creativepsyco** [comment]
sounds good.
