### ISSUE TITLE
Create "Add To Calendar" feature at the bottom of the Event's Detail Page

### ISSUE THREAD

**Issue by jurvis** [fossasia/open-event-ios#6]
<img width="435 alt="screenshot" src="https://cloud.githubusercontent.com/assets/5944973/13031147/7e19666e-d2fc-11e5-9a5d-7e7286af7075.png">

button will look something like this

![screen shot 2016-02-14 at 12 17 11 pm](https://cloud.githubusercontent.com/assets/5944973/13031828/f30e21ae-d314-11e5-9dbc-24acfe8f204f.png)

**Comment by jurvis** [comment]
Asset download: [add_to_cal_button.zip](https://github.com/fossasia/open-event-ios/files/129483/add_to_cal_button.zip)

**Comment by todipratik** [comment]
Working on it.

**Comment by jurvis** [comment]
@todipratik noted. have you started work on this? Thinking I should create a separate Storyboard for the Event page to avoid merge conflicts so I can work on other things without worry

**Comment by todipratik** [comment]
@jurvis Not yet on storyboard part. Having a walkthrough of code. Will need some time. You may separate the storyboard part.

**Comment by leto** [comment]
All the API work on the backend should be working to allow for this. Please let me know if you have questions

**Comment by creativepsyco** [comment]
@leto I think this is just local add to calendar feature, nothing to do with the API, because we want the client to function irrespective of the backend. e.g. via reading regularly pushed JSON Files.
