### ISSUE TITLE
Showing optional values in table cells

### ISSUE THREAD

**Issue by imjog** [fossasia/open-event-ios#62]
In table cells, time of events is showing as optional, `Optional("07:05")`. Optional unwrapping should be done in a good way.

![simulator screen shot - iphone 8 - 2018-05-07 at 01 36 51](https://user-images.githubusercontent.com/20956124/39677572-dee6114e-519a-11e8-8405-19dc0b9cd0cf.png)

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh  may I work on this issue?

**Comment by imjog** [comment]
@SIMRAN1 Sure, go ahead!
