### ISSUE TITLE
Design a splash screen for app

### ISSUE THREAD

**Issue by SIMRAN1** [fossasia/open-event-ios#66]
Currently app doesnot have a splash screen . We can add splash screen to the app .
Would you like to work on this issue?
Yes

**Comment by SIMRAN1** [comment]
@chashmeetsingh @imjog please see this issue!

**Comment by imjog** [comment]
@SIMRAN1 Currently, app have a splash screen. Please see the lauch storyboard. It does not look like splash screen, I agree.

**Comment by imjog** [comment]
@SIMRAN1 Just keep Fossasia logo. Remove others!

**Comment by SIMRAN1** [comment]
okk @imjog !!
